apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: music-pv-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /vagrant/web/Musics
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
