version: "2.1"
services:
  music-player:
    image: music_player:2.2.13
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
        - plateform=windows/amd64

    container_name: music-player
    ports: 
      - 1515:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Developpement
      Shell__TerminalPath: /bin/bash
      Song__Path: /Musics
      YoutubeDl__MusicPath: /app/wwwroot/Musics
      YoutubeDl__Proxy: https://cors-anywhere.herokuapp.com/
      ApplicationVersion: 2.2.13

    volumes:
      - /home/baka/Musique:/app/wwwroot/Musics
    restart: always
