# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

applicationName: music-player

replicaCount: 1

image:
  repository: bakayarusama/music_player
  pullPolicy: Always
  # pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: 
  kompose.cmd: kompose convert
  kompose.version: 1.26.0 (40646f47)

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

volumeMounts:
  - mountPath: /app/wwwroot/Musics
    name: music-player-music
  - mountPath: /https/
    name: music-player-certificate

volumes:
  - name: music-player-music
    persistentVolumeClaim:
      claimName: music-player-music-claim
  - name: music-player-certificate
    persistentVolumeClaim:
      claimName: music-player-certificate-claim

service:
  type: NodePort
  port: 1515

ingress:
  enabled: true
  className: ""
  annotations:
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # kubernetes.io/tls-acme: "true"
  host: baka-music.ddns.net
  
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

environmentVar:
  aspnetcore:
    env: Production
    port: "1515"
    privateKey: "/https/private.key"
    certificate: "/https/certificate.crt"
    urls: "https://+:1515"
  
  log:
    url : "https://baka.elk.ddns.net/api/Log"
  
  shell:
    terminalPath: "/bin/bash"
  
  song:
    path: "/Musics"

  youtubeDl:
    musicPath: "/app/wwwroot/Musics"
    proxy: "https://cors-anywhere.herokuapp.com/"