name: MusicPlayer

on:
  push:
    tags: 
      - '*'

jobs:
  CICD:
    runs-on: ubuntu-latest
    env:
      Repo: /home/runner/work/MusicPlayer/MusicPlayer/MusicPlayer/
      DockerImageName: bakayarusama/music_player:${{  github.ref_name }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Build Docker image
      working-directory: /home/runner/work/MusicPlayer/MusicPlayer/MusicPlayer/
      run: docker build -t $DockerImageName $Repo

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} 
             -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Publish Docker image
      run: docker push $DockerImageName