name: MusicPlayer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Continuous-integration:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      
    - name: Install SDK 5.0
      run: sudo apt-get install dotnet-sdk-5.0
        
    - name: Install dependencies
      working-directory: /home/runner/work/MusicPlayer/MusicPlayer/MusicPlayer
      run: dotnet restore
    
    - name: Build
      working-directory: /home/runner/work/MusicPlayer/MusicPlayer/MusicPlayer
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      working-directory: /home/runner/work/MusicPlayer/MusicPlayer/MusicPlayer
      run: dotnet test --no-restore --verbosity normal

  Continuous_delivery:
    needs: [Continuous-integration]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ bakayrusama }}
        password: ${{ 387b0e1d-0014-45d6-934d-adc253d1ff5b }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: /home/runner/work/MusicPlayer/MusicPlayer/MusicPlayer/MusicPlayerApplication/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: bakayarusama/music_player:latest