name: MusicPlayer

on:
  push:
    tags: 
      - '*'

jobs:
  CICD:
    runs-on: ubuntu-latest
    env:
      Repo: /home/runner/work/MusicPlayer/MusicPlayer/MusicPlayer/
      DockerImageName: bakayarusama/music_player:${{  github.ref_name }}
      Registry: docker-registry.brendan-giraudet.com

    steps:
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Build Docker image
      working-directory: /home/runner/work/MusicPlayer/MusicPlayer/MusicPlayer/
      run: docker build -t $DockerImageName $Repo

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        registry: docker-registry.brendan-giraudet.com 

    - name: Publish Docker image
      run: docker push docker-registry.brendan-giraudet.com/$DockerImageName
