name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Continuous-integration:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    - name: Install dependencies
      working-directory: /home/runner/work/MusicPlayer/MusicPlayer/MusicPlayer
      run: dotnet restore
    
    - name: Build
      working-directory: /home/runner/work/MusicPlayer/MusicPlayer/MusicPlayer
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      working-directory: /home/runner/work/MusicPlayer/MusicPlayer/MusicPlayer
      run: dotnet test --no-restore --verbosity normal
